Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Data.Interfaces;

namespace MotoHelp.Controllers
{
    [Route("about")]
    public class AboutController : Controller
    {
        private readonly ITextFieldsRepository textFieldsRepository;
        public AboutController(ITextFieldsRepository textFieldsRepository)
        {
            this.textFieldsRepository = textFieldsRepository;
        }
        public IActionResult Index()
        {
            var page = textFieldsRepository.GetTextFieldByPageName("PageAbout");
            return View(page);
        }
    }
}

Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Data.Interfaces;
using MotoHelp.Models;

namespace MotoHelp.Controllers
{
    [Route("catalog/{category?}")]
    public class DetailsController : Controller
	{
		private readonly IGetDetails details;
		private readonly IGetDetailCategories categories;
		public DetailsController(IGetDetails _details, IGetDetailCategories _categories)
		{
			details = _details;
			categories = _categories;
		}
        [Route("")]
        public IActionResult Index(string? category)
		{
			IEnumerable<MHDetail> getDetails;
			if (category != null) 
			{
				getDetails = details.GetDetailsByCategory(category);
				MHCategory getCategory = categories.GetCategoryByUrl(category);
				if (getCategory == null) {
					return NotFound();
				}
				ViewBag.Title = getCategory.Name;
				ViewBag.Description = getCategory.Description;
				ViewBag.CurrentCategory = getCategory.Url;
            }
            else
			{
				getDetails = details.details;
				ViewBag.Title = "Запчасти";
			}
			ViewBag.Categories = categories.categories;
            return View(getDetails);
		}
		[Route("{id:int}")]
        public IActionResult Detail(int id)
        {            
            var detail = details.GetDetailById(id);
            return View(detail);
        }
    }
}

Controllers/PersonalController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Models;
using MotoHelp.ViewModels;
using System.Security.Claims;
using MotoHelp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace MotoHelp.Controllers
{
    [Route("personal/{action=Index}")]
    public class PersonalController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public PersonalController(DBContent dBContent, UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr) {
            userManager = userMgr;
            signInManager = signinMgr;
        }
        [HttpGet]
        [ActionName("login")]
        public IActionResult Login(string? ReturnUrl)
        {
            return View(new LoginModel { ReturnUrl = ReturnUrl});
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.Email);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginModel.Email), "Неверный логин или пароль");
            }
            return View(model);
        }
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        //    public async Task<IActionResult> Login(LoginModel model)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            IdentityUser user = await userManager.FindByNameAsync(model.Email); 
        //            if (user != null)
        //            {
        //                await Authenticate(model.Email); // аутентификация
        //                if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
        //                {
        //                    return Redirect(model.ReturnUrl);
        //                }
        //                else
        //                    return RedirectToAction("Index", "Personal");
        //            }
        //            ModelState.AddModelError("", "Некорректные логин и(или) пароль");
        //        }
        //        return View(model);
        //    }
        //    [HttpGet]
        //    public IActionResult Register()
        //    {
        //        return View();
        //    }
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public async Task<IActionResult> Register(RegisterModel model)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            IdentityUser user = await dBContent.Users.FirstOrDefaultAsync(u => u.Email == model.Email);
        //            if (user == null)
        //            {
        //                // добавляем пользователя в бд
        //                dBContent.Users.Add(new IdentityUser { Email = model.Email, PasswordHash = model.Password });
        //                await dBContent.SaveChangesAsync();

        //                await Authenticate(model.Email); // аутентификация

        //                return RedirectToAction("Index", "Home");
        //            }
        //            else
        //                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
        //        }
        //        return View(model);
        //    }

        //    private async Task Authenticate(string userName)
        //    {
        //        // создаем один claim
        //        var claims = new List<Claim>
        //        {
        //            new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
        //        };
        //        // создаем объект ClaimsIdentity
        //        ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
        //        // установка аутентификационных куки
        //        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        //    }

        //    public async Task<IActionResult> Logout()
        //    {
        //        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        //        return RedirectToAction("login", "Personal");
        //    }
    }
}

Controllers/ServicesController.cs
using MotoHelp.Data.Interfaces;
using MotoHelp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MotoHelp.Controllers
{
    [Route("services")]
    public class ServicesController : Controller
    {

        private readonly IGetServices _getServices;

        public ServicesController(IGetServices getServices)
        {
            _getServices = getServices;
        }
        public IActionResult Index()
        {
            ViewBag.Title = "Услуги";
            var serviceList = _getServices.activeServices;
            return View(serviceList);
        }

        [HttpPost]
        [Route("detail/{id}")]
        public IActionResult Detail(int id)
        {
            var service = _getServices.GetService(id);
            return PartialView(service);
        }

    }
}

Views/Shared/AdminHeaderPartial.cshtml
@{
    string controllerName = ViewContext.RouteData.Values["controller"].ToString();
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light border-bottom box-shadow fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img width="150" src="~/images/logo.png"></img>
                </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                <ul class="navbar-nav nav-tabs ms-lg-auto text-center">
                    <li class="nav-item">
                        <a class="nav-link@(controllerName == "TextFields" ? " active" : "")" asp-area="Admin" asp-controller="TextFields" asp-action="Index">Страницы сайта</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link@(controllerName == "GetServices" ? " active" : "")" asp-area="Admin" asp-controller="GetServices" asp-action="Index">Редактировать услуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link@(controllerName == "GetDetails" ? " active" : "")" asp-area="Admin" asp-controller="GetDetails" asp-action="Index">Редактировать запчасти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link@(controllerName == "Calls" ? " active" : "")" asp-area="Admin" asp-controller="Calls" asp-action="Index">Управление звонками</a>
                    </li>                   
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Вернуться на сайт</a>
                    </li>
                </ul>
            </div>
        </div>        
    </nav>
</header>

Views/Shared/CssPartial.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/owl.carousel.min.css" asp-append-version="false" />
<link rel="stylesheet" href="~/css/owl.theme.green.min.css" asp-append-version="false" />

Views/Shared/FooterPartial.cshtml
<footer class="border-top footer text-muted" style="position: inherit">
    <div class="container">
        &copy; 2023 - MotoHelp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
    </div>
</footer>

Views/Shared/HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark border-bottom box-shadow fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img width="150" src="~/images/logo.png"></img>
                @*MotoHelp*@
                </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                <ul class="navbar-nav ms-lg-auto text-center">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Details" asp-action="Index" asp-route-category="">Запчасти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="About" asp-action="Index">О компании</a>
                    </li>
                    <li class="nav-item">
                        <button class="btn btn-success rounded-pill mb-3 mb-lg-0" type="button" data-bs-toggle="modal" data-bs-target="#orderCall">Записаться на ремонт</button>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link d-flex justify-content-center" asp-controller="Personal" asp-action="Index">
                            <div class="d-lg-none me-2">Личный кабинет</div>
                            <svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="25" height="25" viewBox="0 0 396.884 509.009" enable-background="new 0 0 396.884 509.009" xml:space="preserve">
                                <g>
                                    <g>
                                        <path fill="currentColor" d="M305.398,106.962c0,59.069-47.886,106.956-106.956,106.956c-59.075,0-106.963-47.887-106.963-106.956
			                                C91.479,47.887,139.367,0,198.442,0C257.512,0,305.398,47.887,305.398,106.962z" />
                                    </g>
                                    <g>
                                        <path fill="currentColor" d="M198.442,258.486L198.442,258.486C88.844,258.486,0,347.333,0,456.936l0,0
			                                c0,28.752,23.315,52.073,52.073,52.073H344.81c28.754,0,52.074-23.321,52.074-52.073l0,0
			                                C396.884,347.333,308.037,258.486,198.442,258.486z" />
                                    </g>
                                </g>
                            </svg>
                        </a>
                    </li>*@
                </ul>
                <div></div>
            </div>
        </div>
    </nav>
</header>
<div class="modal fade" id="orderCall" tabindex="-1" aria-labelledby="orderCallLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orderCallLabel">Заказать звонок</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="orderCallForm">
                    <div class="mb-3">
                        <label for="ordelCallName">Имя</label>
                        <input type="text" class="form-control" name="Name" aria-describedby="emailHelp" placeholder="Имя">
                    </div>
                    <div class="mb-3">
                        <label for="orderCallPhone">Телефон</label>
                        <input type="text" class="form-control" name="Phone" placeholder="+7 (___) ___-__-__" required>
                    </div>
                    <div class="mb-3">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="personalDataCheck" required>
                            <label class="form-check-label" for="personalDataCheck">Я принимаю <a class="link-primary" target="_blank" asp-area="" asp-controller="Home" asp-action="Privacy">Соглашение об использовании персональных данных</a></label>
                        </div>
                    </div>
                </form>
                <div class="alert alert-success d-none">Сообщение отправлено, мы свяжемся с вами в ближайшее время.</div>
                <div class="alert alert-danger d-none">Ошибка. Данные не отправлены.</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" form="orderCallForm" class="btn btn-primary rounded-pill">Отправить</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/MetaPartial.cshtml
@using MotoHelp.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

@if (ViewBag.Title != null)
{
    <title>MotoHelp | @ViewBag.Title</title>    
}
else
{
    <title>@MHConfig.CompanyName</title>    
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
else
{
    <meta name="description" content="MotoHelp - лучший сервис по ремонту и обслуживанию мототехники"/>  
}

Views/Shared/ScriptsPartial.cshtml
@*<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>*@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="~/js/scripts.js" asp-append-version="true"></script>
<script src="~/js/jquery.inputmask.min.js" asp-append-version="false"></script>
<script src="~/js/owl.carousel.min.js" asp-append-version="false"></script>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    @await Html.PartialAsync("MetaPartial")
    @await Html.PartialAsync("CssPartial")
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

</head>
<body>

    @await Html.PartialAsync("AdminHeaderPartial")

    <main role="main" class="pt-5 pb-3">
        <div class="container mt-5">
            @RenderBody()
        </div>
    </main>

    @await Html.PartialAsync("FooterPartial")
    @await Html.PartialAsync("ScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    @await Html.PartialAsync("MetaPartial")
    @await Html.PartialAsync("CssPartial")
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

</head>
<body>

    @await Html.PartialAsync("HeaderPartial")

    <main role="main" class="pt-5 pb-3">
        <div class="container mt-5">
            @RenderBody()
        </div>
    </main>

    @await Html.PartialAsync("FooterPartial")
    @await Html.PartialAsync("ScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>