Areas/Admin/Controllers/GetDetailsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Data;
using MotoHelp.Data.Interfaces;
using MotoHelp.Models;
using MotoHelp.Service;

namespace MotoHelp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/details/{action=Index}")]
    [Authorize]
    public class GetDetailsController : Controller
    {
        private readonly ILogger _logger;
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public GetDetailsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment, ILogger<GetDetailsController> logger)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(dataManager);
        }

        public IActionResult Edit(int id)
        {
            var entity = id == default ? new MHDetail() : dataManager.GetDetails.GetDetailById(id);

            var categories = dataManager.GetDetailCategories.categories.ToList();
            ViewBag.Categories = categories;

            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(MHDetail model, IFormFile? titleImageFile, IEnumerable<IFormFile>? additionalImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    string fileName = $"{Guid.NewGuid()}{Path.GetExtension(titleImageFile.FileName)}";
                    try
                    {
                        using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", fileName), FileMode.Create))
                        {
                            titleImageFile.CopyTo(stream);
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError($"Ошибка сохранения файла\n{ex}");
                    }

                    if (model.TitlePictire != null)
                    {
                        model.TitlePictire.Uri = fileName;
                    }
                    else
                    {
                        model.TitlePictire = new ImageUri() { Uri = fileName };
                    }                    
                }
                if (additionalImageFile != null)
                {
                    foreach (var file in additionalImageFile)
                    {
                        string fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                        model.AdditionalPictures.Add(new ImageUri(){ Uri = fileName });

                        using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", fileName), FileMode.Create))
                        {
                            file.CopyTo(stream);
                        }
                    }
                }
                dataManager.GetDetails.EditDetail(model);
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var categories = dataManager.GetDetailCategories.categories.ToList();
            ViewBag.Categories = categories;

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            dataManager.GetDetails.DeleteDetail(id);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
        public IActionResult GetDetails()
        {
            return PartialView();
        }
        [ActionName("removepic")]
        [HttpPost]
        public void RemovePicture (int picId, int detId)
        {
            MHDetail detail = dataManager.GetDetails.GetDetailById(detId);
            if (detail != null)
            {                
                var picture = dataManager.ImagesRepository.GetImageUri(picId);
                dataManager.ImagesRepository.Delete(picId);
            }
        }
    }
}

Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Data;

namespace MotoHelp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Data.Interfaces;
using MotoHelp.Models;

namespace MotoHelp.Controllers
{
	public class HomeController : Controller
    {
        private readonly ITextFieldsRepository textFieldsRepository;
        public HomeController (ITextFieldsRepository textFieldsRepository)
        {
            this.textFieldsRepository = textFieldsRepository;
        }
		public IActionResult Index()
        {
            TextField page = textFieldsRepository.GetTextFieldByPageName("PageIndex");
            return View(page);
        }
        [Route("privacy")]
        public IActionResult Privacy()
        {
            TextField page = textFieldsRepository.GetTextFieldByPageName("PagePrivacy");
            return View(page);
        }

    }
}

Controllers/PersonalController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using MotoHelp.Models;
using MotoHelp.ViewModels;
using System.Security.Claims;
using MotoHelp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace MotoHelp.Controllers
{
    [Route("personal/{action=Index}")]
    public class PersonalController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public PersonalController(DBContent dBContent, UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr) {
            userManager = userMgr;
            signInManager = signinMgr;
        }
        [HttpGet]
        [ActionName("login")]
        public IActionResult Login(string? ReturnUrl)
        {
            return View(new LoginModel { ReturnUrl = ReturnUrl});
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.Email);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginModel.Email), "Неверный логин или пароль");
            }
            return View(model);
        }
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        //    public async Task<IActionResult> Login(LoginModel model)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            IdentityUser user = await userManager.FindByNameAsync(model.Email); 
        //            if (user != null)
        //            {
        //                await Authenticate(model.Email); // аутентификация
        //                if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
        //                {
        //                    return Redirect(model.ReturnUrl);
        //                }
        //                else
        //                    return RedirectToAction("Index", "Personal");
        //            }
        //            ModelState.AddModelError("", "Некорректные логин и(или) пароль");
        //        }
        //        return View(model);
        //    }
        //    [HttpGet]
        //    public IActionResult Register()
        //    {
        //        return View();
        //    }
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public async Task<IActionResult> Register(RegisterModel model)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            IdentityUser user = await dBContent.Users.FirstOrDefaultAsync(u => u.Email == model.Email);
        //            if (user == null)
        //            {
        //                // добавляем пользователя в бд
        //                dBContent.Users.Add(new IdentityUser { Email = model.Email, PasswordHash = model.Password });
        //                await dBContent.SaveChangesAsync();

        //                await Authenticate(model.Email); // аутентификация

        //                return RedirectToAction("Index", "Home");
        //            }
        //            else
        //                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
        //        }
        //        return View(model);
        //    }

        //    private async Task Authenticate(string userName)
        //    {
        //        // создаем один claim
        //        var claims = new List<Claim>
        //        {
        //            new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
        //        };
        //        // создаем объект ClaimsIdentity
        //        ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
        //        // установка аутентификационных куки
        //        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        //    }

        //    public async Task<IActionResult> Logout()
        //    {
        //        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        //        return RedirectToAction("login", "Personal");
        //    }
    }
}

Areas/Admin/Views/Home/Index.cshtml
@model DataManager
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2 class="text-center">@strTitle</h2>
    <div>
        <h3>Услуги</h3>
        <div class="div-box">
            <a class="btn btn-secondary mb-3" asp-area="Admin" asp-controller="GetServices" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.GetServices.services.Any())
        {
            <div class="rounded overflow-hidden mb-3">
                <table class="table table-success table-striped table-hover m-0">
                    <thead>
                        <tr>
                            <th class="w-75" scope="col">Название</th>
                            <th scope="col">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (MHService entity in Model.GetServices.services)
                        {
                            <tr>
                                <td class="table-row-title">
                                    <div class="mb-2">
                                        @($"{entity.Name}")
                                    </div>
                                </td>
                                <td class="d-flex" align="right">
                                    <a class="btn btn-success me-2" asp-area="Admin" asp-controller="GetServices" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                                    <form class="p-0" id="form-@entity.Id" asp-area="Admin" asp-controller="GetServices" asp-action="Delete" method="post">
                                        <input type="hidden" name="id" value="@entity.Id">
                                        <a class="btn btn-danger" href="#" onclick="confirmDelete(document.getElementById('form-@entity.Id'));">Удалить</a>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
    <div>
        <h3>Товары</h3>
        <div class="div-box">
            <a class="btn btn-secondary mb-3" asp-area="Admin" asp-controller="GetDetails" asp-action="Edit" asp-route-id="">Добавить товар</a>
        </div>
        @if (Model.GetDetails.details.Any())
        {
            <div class="rounded overflow-hidden mb-3">
                <table class="table table-success table-striped table-hover m-0">
                    <thead>
                        <tr>
                            <th class="w-75" scope="col">Название</th>
                            <th scope="col">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (MHDetail entity in Model.GetDetails.details)
                        {
                            <tr>
                                <td class="table-row-title">
                                    <a class="link-primary" asp-area="" asp-route="catalog" asp-route-category="@entity.MHCategory.Url" asp-route-id="@entity.Id">
                                        @($"{entity.Name}")
                                    </a>
                                </td>
                                <td class="d-flex" height="100%">
                                    <a class="btn btn-success me-2" asp-area="Admin" asp-controller="GetDetails" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                                    <form class="p-0" id="form-@entity.Id" asp-area="Admin" asp-controller="GetDetails" asp-action="Delete" method="post">
                                        <input type="hidden" name="id" value="@entity.Id">
                                        <a class="btn btn-danger w-100" href="#" onclick="confirmDelete(document.getElementById('form-@entity.Id'));">Удалить</a>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Personal" asp-action="Logout" method="post">
            <input class="btn btn-danger" type="submit" value="Выйти" />
        </form>
    </div>
</div>

<script>
    function confirmDelete(el) {
        if (confirm('Удалить запись?')) {
            el.submit();
        } else {
            return
        }
    }
</script>